name: Check code formatting

on:
  push:
    branches: [main, pipelines]
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./LoverLoverBoyAPI

      - name: Check formatting
        run: dotnet format --verify-no-changes
        working-directory: ./LoverLoverBoyAPI
